// Generates the package's published files from src/tokens.mjs:
//
//   dist/tokens.css    custom properties: light on :root, dark under
//                      prefers-color-scheme, and [data-theme] to force either
//   dist/_tokens.scss  raw values ($kit-light-accent, …) + palette mixins, for
//                      code that needs literals (e.g. Angular Material palettes)
//   dist/tokens.json   the same data, for scripts and docs
//
// Runs on install (`prepare`) and before publish, so dist/ is never committed.
import { mkdir, writeFile } from 'node:fs/promises';
import { brand, fonts, palette } from './src/tokens.mjs';

const lightKeys = Object.keys(palette.light);
const darkKeys = Object.keys(palette.dark);
const missing = [
  ...lightKeys.filter((k) => !darkKeys.includes(k)).map((k) => `dark.${k}`),
  ...darkKeys.filter((k) => !lightKeys.includes(k)).map((k) => `light.${k}`),
];
if (missing.length) {
  console.error(
    `Every palette role needs a light and a dark value. Missing: ${missing.join(', ')}`,
  );
  process.exit(1);
}

const decls = (obj, indent) =>
  Object.entries(obj)
    .map(([k, v]) => `${indent}--${k}: ${v};`)
    .join('\n');

const header = '/* Generated by @kiskinvlad/linker-tokens from src/tokens.mjs. Do not edit. */\n';

const css = `${header}
:root {
${decls(brand, '  ')}
${decls(fonts, '  ')}
${decls(palette.light, '  ')}
  color-scheme: light dark;
}

/* Follows the OS unless a page pins a theme with data-theme on <html>.
   Plain :root in the media query, and the light pin re-declared below, rather
   than :root:not([data-theme='light']): critical-CSS inliners (Angular's Beasties)
   drop the :not() form, which left dark-mode visitors a light first paint. */
@media (prefers-color-scheme: dark) {
  :root {
${decls(palette.dark, '    ')}
  }
}

:root[data-theme='dark'] {
${decls(palette.dark, '  ')}
  color-scheme: dark;
}

:root[data-theme='light'] {
${decls(palette.light, '  ')}
  color-scheme: light;
}
`;

const scssVars = (prefix, obj) =>
  Object.entries(obj)
    .map(([k, v]) => `$${prefix}${k}: ${v};`)
    .join('\n');
const mixin = (name, mode) =>
  `@mixin ${name} {\n${Object.keys(palette[mode])
    .map((k) => `  --${k}: #{$kit-${mode}-${k}};`)
    .join('\n')}\n}`;

const scss = `// Generated by @kiskinvlad/linker-tokens from src/tokens.mjs. Do not edit.
// Raw values for code that needs literals; the custom properties are in tokens.css.

${scssVars('kit-', brand)}

${scssVars('kit-', fonts)}

${scssVars('kit-light-', palette.light)}

${scssVars('kit-dark-', palette.dark)}

// Emit a whole palette as custom properties, e.g. \`:root { @include kit-palette-dark; }\`
// for an app whose default is dark.
${mixin('kit-palette-light', 'light')}

${mixin('kit-palette-dark', 'dark')}
`;

await mkdir('dist', { recursive: true });
await writeFile('dist/tokens.css', css);
await writeFile('dist/_tokens.scss', scss);
await writeFile('dist/tokens.json', `${JSON.stringify({ brand, fonts, palette }, null, 2)}\n`);
console.log(
  `tokens: ${lightKeys.length} palette roles, ${Object.keys(brand).length} brand colours`,
);
